sonar.projectKey=Darli963_Infra_Proyecto
sonar.organization=darli963
sonar.projectName=Infra_Proyecto
sonar.sourceEncoding=UTF-8

sonar.sources=api-sistema-cotizacion/backend/src,api-sistema-cotizacion/backend/prisma,api-sistema-cotizacion/frontend/src,terraform,ansible

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.terraform/**,**/*.tfstate,**/*.tfstate.*,**/*.tfplan,**/docs/**,**/*.png,**/package-lock.json,terraform/modules/audit/**

sonar.terraform.provider.aws.version=5.100.0
