plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Project: infra-proyecto

hostnames:
  - instance-id

compose:
  ansible_host: instance_id

keyed_groups:
  - key: tags.Environment
    prefix: env

groups:
  phase4_test: tags.Phase is defined and tags.Phase == 'phase4'
  deploy_dev: tags.Environment is defined and tags.Environment == 'dev' and tags.Phase is defined and tags.Phase == 'phase4'
  deploy_prod: tags.Environment is defined and tags.Environment == 'prod' and ((tags.Role is defined and tags.Role == 'app-server') or (tags.Phase is defined and tags.Phase == 'phase4'))
