plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Phase: phase4

hostnames:
  - instance-id

compose:
  ansible_host: instance_id

keyed_groups:
  - key: tags.Environment
    prefix: env

groups:
  phase4_test: tags.Phase is defined and tags.Phase == 'phase4'
