name: CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - "feat/**"
      - "fix/**"
      - "infra/**"
      - "ci/**"
      - "refactor/**"
      - "chore/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform ${{ matrix.environment }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: us-east-1
      AWS_EC2_METADATA_DISABLED: "true"
    strategy:
      fail-fast: false
      matrix:
        environment:
          - dev
          - prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform fmt
        run: terraform fmt -check -recursive "${{ github.workspace }}/terraform"

      - name: Terraform init
        working-directory: terraform/environments/${{ matrix.environment }}
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: us-east-1
          AWS_EC2_METADATA_DISABLED: "true"
        run: terraform init -reconfigure

      - name: Debug
        working-directory: terraform/environments/${{ matrix.environment }}
        run: |
          pwd
          ls -la
          ls -la .terraform

      - name: Terraform validate
        working-directory: terraform/environments/${{ matrix.environment }}
        run: terraform validate

      - name: Terraform plan
        working-directory: terraform/environments/${{ matrix.environment }}
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: us-east-1
          AWS_EC2_METADATA_DISABLED: "true"
        run: terraform plan -refresh=false -lock=false -input=false -var-file="${{ matrix.environment }}.tfvars"
